module.exports = Object.freeze({
    LABEL_API_ROOT: '/',
    LABEL_API_GET_MAP: '/get-map',
    LABEL_API_CREATE_MAP: '/create-map',
    LABEL_API_ADD_NEW:'/add-new-map',
    LABEL_API_REMOVE_MAP:'/remove-map',
    LABEL_API_SAVE_MAP:'/save-map',
    LABEL_API_SAVE_SEAT:'/save-seat',
    LABEL_API_GET_MAPS:'/get-maps',

    LOGIN_API_LABEL:'/login',
    SIGNUP_API_LABEL:'/signup',
    HOME_API_LABEL: '/home',
    RECORD_API_LABEL: '/record',

    ERROR_API_LABEL: '/error',
    FORGOT_PASSWORD_API_LABEL:'/forgot',
    SEND_MAIL_API_LABEL: '/sendMail',
    RESET_API_LABEL:'/reset',
    RESET_PASSWORD_API_LABEL:'/resetPassword',

    //ERROR_MSGS

    INVALID_PARAM_ERROR_MSG: 'One or more paramater was invalid',
    SUCCESS_MSG: 'Success!',
    FAILURE_MSG: 'Fail!',


    //ERROR CODES
    ITEM_ALREADY_PRSENT_ERRORCODE: 'DUPLICATE_ITEM_ERROR',
    USER_NOT_FOUND_ERRORCODE: 'USERNAME_NOT_FOUND',
    INVALID_PARAM_ERRORCODE: 'INVALID_PARAM',
    DB_ERRORCODE: 'DB_ERROR',
    CRYPTO_ERRORCODE: 'BCRYPT_ERROR',
    NO_RESULT_FROM_DB_ERRORCODE: 'NO_RESULT_FROM_DB',
    AUTHENTICATION_FAILURE_ERRORCODE: 'INVALID_PASSWORD',
    TOKEN_AUTHENTICATION_FAILURE_ERRORCODE: 'INVALID_TOKEN',
    INDEX_OUT_OF_BOUNDS_ERRORCODE: 'INDEX_OUT_OF_BOUNDS',
    INVALID_PATH_ERRORCODE: 'INVALID_PATH',
    PARAM_TO_BE_RETRIEVED_NOT_RECOGNIZED: "INVALID REQUEST PARAMETER",

    //COLLECTION NAMES
    COLLECTION_MAP :"map",
    COLLECTION_EMP:"employee"
});